### ISSUE TITLE
derivative_on_space

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [UniFormal/physics#3]
Hi there,

I don't quite get what derivative_on_space is supposed to do here... could you please explain, or consider removing it as direct numerical differentiation is numerically not stable [0]

Thanks!

[0] https://de.wikipedia.org/wiki/Numerische_Differentiation

**Comment by aaleryani** [comment]
Hello freifrauvonbleifrei,
The emphasis of this project right now is in exposing type-checked MMT MPDs (physical models) theories to programming languages that can use them in computations/simulations. So it's not our focus to create a numerical framework here, as there are plenty of these already.

Nonetheless, you're right about the function's instability.  Thank you for your feedback.
